import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "@/components/footer";

const notoSerif = Noto_Serif({
  weight: ['400', '700'], // Specify weights you'll use
  style: ['normal', 'italic'],
  subsets: ['latin'], // Add more if needed
});

export const metadata: Metadata = {
  title: "GAZA SOUP KITCHEN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerif} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
